name: PlatformIO Build

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.10"

            - name: Set up PlatformIO
              run: python3 -m pip install platformio

            #   copy include/JMCredentials.example.hpp to include/JMCredentials.hpp
            - name: Copy JMCredentials.example.hpp to JMCredentials.hpp
              run: cp include/JMCredentials.example.hpp include/JMCredentials.hpp

            - name: Install platformIO dependencies
              run: platformio pkg install

            - name: Build firmware
              run: platformio run
